apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/la-belle-femme/Deploying-and-Optimizing-a-Production-Grade-Kibana-Chart-with-ArgoCD.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: elk-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
